In [5]:
import numpy as np

temperatures = np.genfromtxt('temperature_data.csv', delimiter = ',')


temperatures_fixed = temperatures + 3
print("  ")
print(temperatures_fixed)

monday_temperatures = temperatures_fixed[0, 0:4]
print("  ")
print(monday_temperatures)

thursday_friday_morning = temperatures_fixed[3:5, 1]
print("  ")
print(thursday_friday_morning)


temperature_50 = temperatures_fixed[(temperatures_fixed < 50)]
temperature_60 = temperatures_fixed[(temperatures_fixed > 60)]

print("  ")

print(temperature_50)
print("  ")
print(temperature_60)
print("  ")
temperature_extremes = temperatures_fixed[(temperatures_fixed < 50) | (temperatures_fixed > 60)]
print(temperature_extremes)

  
[[46.6 48.1 61.8 56. ]
 [50.  47.5 61.3 55.6]
 [49.7 47.2 60.9 55.2]
 [49.5 47.1 60.6 54.9]
 [49.2 46.9 60.2 54.5]]
  
[46.6 48.1 61.8 56. ]
  
[47.1 46.9]
  
[46.6 48.1 47.5 49.7 47.2 49.5 47.1 49.2 46.9]
  
[61.8 61.3 60.9 60.6 60.2]
  
[46.6 48.1 61.8 47.5 61.3 49.7 47.2 60.9 49.5 47.1 60.6 49.2 46.9 60.2]
